2024-12-28 16:37:26,746 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 16:37:26] "GET / HTTP/1.1" 200 -
2024-12-28 16:37:26,770 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 16:37:26] "[36mGET /static/css/Login_page.css HTTP/1.1[0m" 304 -
2024-12-28 16:37:26,805 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 16:37:26] "[33mGET /static/images/background.jpg HTTP/1.1[0m" 404 -
2024-12-28 16:37:32,665 - INFO - main.py - User 'zura' logged in successfully.
2024-12-28 16:37:32,666 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 16:37:32] "[32mPOST / HTTP/1.1[0m" 302 -
2024-12-28 16:37:32,684 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 16:37:32] "GET /index HTTP/1.1" 200 -
2024-12-28 16:37:32,723 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 16:37:32] "[36mGET /static/css/map_page.css HTTP/1.1[0m" 304 -
2024-12-28 16:37:40,824 - INFO - main.py - User 'zura' submitted filter data: start_date=2024-10-16, end_date=2024-12-28, callsign_filter=both, id_filter=.
2024-12-28 16:37:40,891 - ERROR - app.py - Exception on /index [POST]
Traceback (most recent call last):
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\pandas\core\indexes\base.py", line 3361, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Altitude_1'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "E:\ZURA KOPADZE\mapping_stca\main.py", line 130, in index
    start_date, end_date, callsign_filter, id_filter
  File "E:\ZURA KOPADZE\mapping_stca\Map.py", line 135, in create_map
    f"<div style='font-size: 18px;'>"
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\pandas\core\series.py", line 942, in __getitem__
    return self._get_value(key)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\pandas\core\series.py", line 1051, in _get_value
    loc = self.index.get_loc(label)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\pandas\core\indexes\base.py", line 3363, in get_loc
    raise KeyError(key) from err
KeyError: 'Altitude_1'
2024-12-28 16:37:40,897 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 16:37:40] "[35m[1mPOST /index HTTP/1.1[0m" 500 -
2024-12-28 16:38:49,893 - INFO - main.py - Flask application is shutting down.
2024-12-28 16:38:57,597 - INFO - _internal.py - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://192.168.1.59:80
2024-12-28 16:38:57,597 - INFO - _internal.py - [33mPress CTRL+C to quit[0m
2024-12-28 16:38:58,016 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 16:38:58] "GET / HTTP/1.1" 200 -
2024-12-28 16:38:58,041 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 16:38:58] "[36mGET /static/css/Login_page.css HTTP/1.1[0m" 304 -
2024-12-28 16:38:58,082 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 16:38:58] "[33mGET /static/images/background.jpg HTTP/1.1[0m" 404 -
2024-12-28 16:38:58,107 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 16:38:58] "[36mGET /static/international-travel_14098668.png HTTP/1.1[0m" 304 -
2024-12-28 16:39:02,924 - INFO - main.py - User 'zura' logged in successfully.
2024-12-28 16:39:02,925 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 16:39:02] "[32mPOST / HTTP/1.1[0m" 302 -
2024-12-28 16:39:02,941 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 16:39:02] "GET /index HTTP/1.1" 200 -
2024-12-28 16:39:02,979 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 16:39:02] "[36mGET /static/css/map_page.css HTTP/1.1[0m" 304 -
2024-12-28 16:39:11,094 - INFO - main.py - User 'zura' submitted filter data: start_date=2024-10-17, end_date=2024-11-14, callsign_filter=both, id_filter=.
2024-12-28 16:39:11,150 - ERROR - app.py - Exception on /index [POST]
Traceback (most recent call last):
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\pandas\core\indexes\base.py", line 3361, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Altitude_1'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "E:\ZURA KOPADZE\mapping_stca\main.py", line 130, in index
    start_date, end_date, callsign_filter, id_filter
  File "E:\ZURA KOPADZE\mapping_stca\Map.py", line 135, in create_map
    f"<div style='font-size: 18px;'>"
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\pandas\core\series.py", line 942, in __getitem__
    return self._get_value(key)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\pandas\core\series.py", line 1051, in _get_value
    loc = self.index.get_loc(label)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\pandas\core\indexes\base.py", line 3363, in get_loc
    raise KeyError(key) from err
KeyError: 'Altitude_1'
2024-12-28 16:39:11,157 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 16:39:11] "[35m[1mPOST /index HTTP/1.1[0m" 500 -
2024-12-28 16:42:17,807 - INFO - main.py - Flask application is shutting down.
2024-12-28 16:42:25,687 - INFO - _internal.py - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://192.168.1.59:80
2024-12-28 16:42:25,687 - INFO - _internal.py - [33mPress CTRL+C to quit[0m
2024-12-28 16:42:26,198 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 16:42:26] "GET / HTTP/1.1" 200 -
2024-12-28 16:42:26,224 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 16:42:26] "[36mGET /static/css/Login_page.css HTTP/1.1[0m" 304 -
2024-12-28 16:42:26,261 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 16:42:26] "[33mGET /static/images/background.jpg HTTP/1.1[0m" 404 -
2024-12-28 16:42:26,289 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 16:42:26] "[36mGET /static/international-travel_14098668.png HTTP/1.1[0m" 304 -
2024-12-28 16:42:33,287 - INFO - main.py - User 'zura' logged in successfully.
2024-12-28 16:42:33,289 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 16:42:33] "[32mPOST / HTTP/1.1[0m" 302 -
2024-12-28 16:42:33,306 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 16:42:33] "GET /index HTTP/1.1" 200 -
2024-12-28 16:42:33,333 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 16:42:33] "[36mGET /static/css/map_page.css HTTP/1.1[0m" 304 -
2024-12-28 16:42:43,112 - INFO - main.py - User 'zura' submitted filter data: start_date=2024-07-18, end_date=2024-11-28, callsign_filter=both, id_filter=.
2024-12-28 16:42:47,016 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 16:42:47] "POST /index HTTP/1.1" 200 -
2024-12-28 16:42:47,045 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 16:42:47] "[36mGET /static/css/map_page.css HTTP/1.1[0m" 304 -
2024-12-28 16:42:47,129 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 16:42:47] "GET /Results/index.html HTTP/1.1" 200 -
2024-12-28 16:43:52,778 - INFO - main.py - Flask application is shutting down.
2024-12-28 16:44:00,456 - INFO - _internal.py - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://192.168.1.59:80
2024-12-28 16:44:00,456 - INFO - _internal.py - [33mPress CTRL+C to quit[0m
2024-12-28 16:44:04,194 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 16:44:04] "GET / HTTP/1.1" 200 -
2024-12-28 16:44:04,227 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 16:44:04] "[36mGET /static/css/Login_page.css HTTP/1.1[0m" 304 -
2024-12-28 16:44:04,240 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 16:44:04] "[33mGET /static/images/background.jpg HTTP/1.1[0m" 404 -
2024-12-28 16:44:08,941 - INFO - main.py - User 'zura' logged in successfully.
2024-12-28 16:44:08,942 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 16:44:08] "[32mPOST / HTTP/1.1[0m" 302 -
2024-12-28 16:44:08,961 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 16:44:08] "GET /index HTTP/1.1" 200 -
2024-12-28 16:44:08,997 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 16:44:08] "[36mGET /static/css/map_page.css HTTP/1.1[0m" 304 -
2024-12-28 16:44:16,541 - INFO - main.py - User 'zura' submitted filter data: start_date=2024-10-23, end_date=2024-12-29, callsign_filter=both, id_filter=.
2024-12-28 16:44:17,917 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 16:44:17] "POST /index HTTP/1.1" 200 -
2024-12-28 16:44:17,948 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 16:44:17] "[36mGET /static/css/map_page.css HTTP/1.1[0m" 304 -
2024-12-28 16:44:18,012 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 16:44:18] "GET /Results/index.html HTTP/1.1" 200 -
2024-12-28 16:46:25,802 - INFO - main.py - Flask application is shutting down.
2024-12-28 16:55:47,456 - INFO - _internal.py - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://192.168.1.59:80
2024-12-28 16:55:47,456 - INFO - _internal.py - [33mPress CTRL+C to quit[0m
2024-12-28 16:55:48,082 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 16:55:48] "GET / HTTP/1.1" 200 -
2024-12-28 16:55:48,113 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 16:55:48] "[36mGET /static/css/Login_page.css HTTP/1.1[0m" 304 -
2024-12-28 16:55:48,143 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 16:55:48] "[33mGET /static/images/background.jpg HTTP/1.1[0m" 404 -
2024-12-28 16:55:48,194 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 16:55:48] "[36mGET /static/international-travel_14098668.png HTTP/1.1[0m" 304 -
2024-12-28 16:55:52,624 - INFO - main.py - User 'zura' logged in successfully.
2024-12-28 16:55:52,626 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 16:55:52] "[32mPOST / HTTP/1.1[0m" 302 -
2024-12-28 16:55:52,646 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 16:55:52] "GET /index HTTP/1.1" 200 -
2024-12-28 16:55:52,676 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 16:55:52] "[36mGET /static/css/map_page.css HTTP/1.1[0m" 304 -
2024-12-28 16:56:02,780 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 16:56:02] "GET /index HTTP/1.1" 200 -
2024-12-28 16:56:02,805 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 16:56:02] "[36mGET /static/css/map_page.css HTTP/1.1[0m" 304 -
2024-12-28 16:56:07,735 - INFO - main.py - User 'zura' logged out successfully.
2024-12-28 16:56:07,736 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 16:56:07] "[32mGET /logout HTTP/1.1[0m" 302 -
2024-12-28 16:56:07,749 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 16:56:07] "GET / HTTP/1.1" 200 -
2024-12-28 16:56:07,779 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 16:56:07] "[36mGET /static/css/Login_page.css HTTP/1.1[0m" 304 -
2024-12-28 16:56:07,828 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 16:56:07] "[33mGET /static/images/background.jpg HTTP/1.1[0m" 404 -
2024-12-28 16:56:16,303 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 16:56:16] "[31m[1mGET /index HTTP/1.1[0m" 401 -
2024-12-28 16:56:21,889 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 16:56:21] "GET / HTTP/1.1" 200 -
2024-12-28 16:56:21,920 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 16:56:21] "[36mGET /static/css/Login_page.css HTTP/1.1[0m" 304 -
2024-12-28 16:56:26,606 - INFO - main.py - User 'zura' logged in successfully.
2024-12-28 16:56:26,607 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 16:56:26] "[32mPOST / HTTP/1.1[0m" 302 -
2024-12-28 16:56:26,617 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 16:56:26] "GET /index HTTP/1.1" 200 -
2024-12-28 16:56:26,645 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 16:56:26] "[36mGET /static/css/map_page.css HTTP/1.1[0m" 304 -
2024-12-28 16:56:35,930 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 16:56:35] "GET /index HTTP/1.1" 200 -
2024-12-28 16:56:35,952 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 16:56:35] "[36mGET /static/css/map_page.css HTTP/1.1[0m" 304 -
2024-12-28 16:56:47,457 - INFO - main.py - User 'zura' submitted filter data: start_date=2024-08-23, end_date=2024-12-26, callsign_filter=both, id_filter=.
2024-12-28 16:56:50,557 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 16:56:50] "POST /index HTTP/1.1" 200 -
2024-12-28 16:56:50,590 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 16:56:50] "[36mGET /static/css/map_page.css HTTP/1.1[0m" 304 -
2024-12-28 16:56:50,666 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 16:56:50] "GET /Results/index.html HTTP/1.1" 200 -
2024-12-28 16:56:59,964 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 16:56:59] "GET /index HTTP/1.1" 200 -
2024-12-28 16:56:59,989 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 16:56:59] "[36mGET /static/css/map_page.css HTTP/1.1[0m" 304 -
2024-12-28 18:21:53,885 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 18:21:53] "[36mGET /static/css/map_page.css HTTP/1.1[0m" 304 -
2024-12-28 18:22:38,118 - INFO - main.py - User 'zura' submitted filter data: start_date=2024-10-28, end_date=2024-11-28, callsign_filter=both, id_filter=.
2024-12-28 18:22:39,093 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 18:22:39] "POST /index HTTP/1.1" 200 -
2024-12-28 18:22:39,144 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 18:22:39] "[36mGET /static/css/map_page.css HTTP/1.1[0m" 304 -
2024-12-28 18:22:39,262 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 18:22:39] "GET /Results/index.html HTTP/1.1" 200 -
2024-12-28 18:25:57,967 - INFO - main.py - Flask application is shutting down.
2024-12-28 18:26:09,632 - INFO - _internal.py - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://172.16.12.13:80
2024-12-28 18:26:09,632 - INFO - _internal.py - [33mPress CTRL+C to quit[0m
2024-12-28 18:26:15,042 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 18:26:15] "GET / HTTP/1.1" 200 -
2024-12-28 18:26:15,089 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 18:26:15] "[36mGET /static/css/Login_page.css HTTP/1.1[0m" 304 -
2024-12-28 18:26:15,142 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 18:26:15] "[33mGET /static/images/background.jpg HTTP/1.1[0m" 404 -
2024-12-28 18:26:29,252 - INFO - main.py - User 'zura' logged in successfully.
2024-12-28 18:26:29,253 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 18:26:29] "[32mPOST / HTTP/1.1[0m" 302 -
2024-12-28 18:26:29,260 - ERROR - app.py - Exception on /index [GET]
Traceback (most recent call last):
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "E:\ZURA KOPADZE\mapping_stca\main.py", line 143, in index
    warning_message=warning_message)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\templating.py", line 146, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\jinja2\environment.py", line 1084, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\jinja2\environment.py", line 1013, in get_template
    return self._load_template(name, globals)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\jinja2\environment.py", line 972, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\templating.py", line 62, in get_source
    return self._get_source_fast(environment, template)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\templating.py", line 98, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: map.html
2024-12-28 18:26:29,343 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 18:26:29] "[35m[1mGET /index HTTP/1.1[0m" 500 -
2024-12-28 18:26:53,783 - INFO - main.py - Flask application is shutting down.
2024-12-28 18:26:57,945 - INFO - _internal.py - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://172.16.12.13:80
2024-12-28 18:26:57,945 - INFO - _internal.py - [33mPress CTRL+C to quit[0m
2024-12-28 18:27:02,884 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 18:27:02] "GET / HTTP/1.1" 200 -
2024-12-28 18:27:02,910 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 18:27:02] "[36mGET /static/css/Login_page.css HTTP/1.1[0m" 304 -
2024-12-28 18:27:03,024 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 18:27:03] "[33mGET /static/images/background.jpg HTTP/1.1[0m" 404 -
2024-12-28 18:27:13,717 - INFO - main.py - User 'zura' logged in successfully.
2024-12-28 18:27:13,718 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 18:27:13] "[32mPOST / HTTP/1.1[0m" 302 -
2024-12-28 18:27:13,726 - ERROR - app.py - Exception on /index [GET]
Traceback (most recent call last):
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "E:\ZURA KOPADZE\mapping_stca\main.py", line 143, in index
    warning_message=warning_message)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\templating.py", line 146, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\jinja2\environment.py", line 1084, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\jinja2\environment.py", line 1013, in get_template
    return self._load_template(name, globals)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\jinja2\environment.py", line 972, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\templating.py", line 62, in get_source
    return self._get_source_fast(environment, template)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\templating.py", line 98, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: map.html
2024-12-28 18:27:13,730 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 18:27:13] "[35m[1mGET /index HTTP/1.1[0m" 500 -
2024-12-28 18:27:16,490 - ERROR - app.py - Exception on /index [GET]
Traceback (most recent call last):
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "E:\ZURA KOPADZE\mapping_stca\main.py", line 143, in index
    warning_message=warning_message)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\templating.py", line 146, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\jinja2\environment.py", line 1084, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\jinja2\environment.py", line 1013, in get_template
    return self._load_template(name, globals)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\jinja2\environment.py", line 972, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\templating.py", line 62, in get_source
    return self._get_source_fast(environment, template)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\templating.py", line 98, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: map.html
2024-12-28 18:27:16,492 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 18:27:16] "[35m[1mGET /index HTTP/1.1[0m" 500 -
2024-12-28 18:27:17,142 - ERROR - app.py - Exception on /index [GET]
Traceback (most recent call last):
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "E:\ZURA KOPADZE\mapping_stca\main.py", line 143, in index
    warning_message=warning_message)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\templating.py", line 146, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\jinja2\environment.py", line 1084, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\jinja2\environment.py", line 1013, in get_template
    return self._load_template(name, globals)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\jinja2\environment.py", line 972, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\templating.py", line 62, in get_source
    return self._get_source_fast(environment, template)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\templating.py", line 98, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: map.html
2024-12-28 18:27:17,144 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 18:27:17] "[35m[1mGET /index HTTP/1.1[0m" 500 -
2024-12-28 18:27:17,368 - ERROR - app.py - Exception on /index [GET]
Traceback (most recent call last):
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "E:\ZURA KOPADZE\mapping_stca\main.py", line 143, in index
    warning_message=warning_message)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\templating.py", line 146, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\jinja2\environment.py", line 1084, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\jinja2\environment.py", line 1013, in get_template
    return self._load_template(name, globals)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\jinja2\environment.py", line 972, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\templating.py", line 62, in get_source
    return self._get_source_fast(environment, template)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\templating.py", line 98, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: map.html
2024-12-28 18:27:17,369 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 18:27:17] "[35m[1mGET /index HTTP/1.1[0m" 500 -
2024-12-28 18:27:17,953 - ERROR - app.py - Exception on /index [GET]
Traceback (most recent call last):
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "E:\ZURA KOPADZE\mapping_stca\main.py", line 143, in index
    warning_message=warning_message)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\templating.py", line 146, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\jinja2\environment.py", line 1084, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\jinja2\environment.py", line 1013, in get_template
    return self._load_template(name, globals)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\jinja2\environment.py", line 972, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\templating.py", line 62, in get_source
    return self._get_source_fast(environment, template)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\templating.py", line 98, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: map.html
2024-12-28 18:27:17,954 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 18:27:17] "[35m[1mGET /index HTTP/1.1[0m" 500 -
2024-12-28 18:27:18,536 - ERROR - app.py - Exception on /index [GET]
Traceback (most recent call last):
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "E:\ZURA KOPADZE\mapping_stca\main.py", line 143, in index
    warning_message=warning_message)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\templating.py", line 146, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\jinja2\environment.py", line 1084, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\jinja2\environment.py", line 1013, in get_template
    return self._load_template(name, globals)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\jinja2\environment.py", line 972, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\templating.py", line 62, in get_source
    return self._get_source_fast(environment, template)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\templating.py", line 98, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: map.html
2024-12-28 18:27:18,538 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 18:27:18] "[35m[1mGET /index HTTP/1.1[0m" 500 -
2024-12-28 18:27:18,969 - ERROR - app.py - Exception on /index [GET]
Traceback (most recent call last):
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "E:\ZURA KOPADZE\mapping_stca\main.py", line 143, in index
    warning_message=warning_message)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\templating.py", line 146, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\jinja2\environment.py", line 1084, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\jinja2\environment.py", line 1013, in get_template
    return self._load_template(name, globals)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\jinja2\environment.py", line 972, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\templating.py", line 62, in get_source
    return self._get_source_fast(environment, template)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\templating.py", line 98, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: map.html
2024-12-28 18:27:18,971 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 18:27:18] "[35m[1mGET /index HTTP/1.1[0m" 500 -
2024-12-28 18:27:19,214 - ERROR - app.py - Exception on /index [GET]
Traceback (most recent call last):
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "E:\ZURA KOPADZE\mapping_stca\main.py", line 143, in index
    warning_message=warning_message)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\templating.py", line 146, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\jinja2\environment.py", line 1084, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\jinja2\environment.py", line 1013, in get_template
    return self._load_template(name, globals)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\jinja2\environment.py", line 972, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\templating.py", line 62, in get_source
    return self._get_source_fast(environment, template)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\templating.py", line 98, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: map.html
2024-12-28 18:27:19,217 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 18:27:19] "[35m[1mGET /index HTTP/1.1[0m" 500 -
2024-12-28 18:27:19,598 - ERROR - app.py - Exception on /index [GET]
Traceback (most recent call last):
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "E:\ZURA KOPADZE\mapping_stca\main.py", line 143, in index
    warning_message=warning_message)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\templating.py", line 146, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\jinja2\environment.py", line 1084, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\jinja2\environment.py", line 1013, in get_template
    return self._load_template(name, globals)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\jinja2\environment.py", line 972, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\templating.py", line 62, in get_source
    return self._get_source_fast(environment, template)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\templating.py", line 98, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: map.html
2024-12-28 18:27:19,602 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 18:27:19] "[35m[1mGET /index HTTP/1.1[0m" 500 -
2024-12-28 18:27:19,926 - ERROR - app.py - Exception on /index [GET]
Traceback (most recent call last):
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "E:\ZURA KOPADZE\mapping_stca\main.py", line 143, in index
    warning_message=warning_message)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\templating.py", line 146, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\jinja2\environment.py", line 1084, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\jinja2\environment.py", line 1013, in get_template
    return self._load_template(name, globals)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\jinja2\environment.py", line 972, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\templating.py", line 62, in get_source
    return self._get_source_fast(environment, template)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\templating.py", line 98, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: map.html
2024-12-28 18:27:19,927 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 18:27:19] "[35m[1mGET /index HTTP/1.1[0m" 500 -
2024-12-28 18:27:20,253 - ERROR - app.py - Exception on /index [GET]
Traceback (most recent call last):
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "E:\ZURA KOPADZE\mapping_stca\main.py", line 143, in index
    warning_message=warning_message)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\templating.py", line 146, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\jinja2\environment.py", line 1084, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\jinja2\environment.py", line 1013, in get_template
    return self._load_template(name, globals)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\jinja2\environment.py", line 972, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\templating.py", line 62, in get_source
    return self._get_source_fast(environment, template)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\templating.py", line 98, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: map.html
2024-12-28 18:27:20,255 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 18:27:20] "[35m[1mGET /index HTTP/1.1[0m" 500 -
2024-12-28 18:27:20,572 - ERROR - app.py - Exception on /index [GET]
Traceback (most recent call last):
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "E:\ZURA KOPADZE\mapping_stca\main.py", line 143, in index
    warning_message=warning_message)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\templating.py", line 146, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\jinja2\environment.py", line 1084, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\jinja2\environment.py", line 1013, in get_template
    return self._load_template(name, globals)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\jinja2\environment.py", line 972, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\templating.py", line 62, in get_source
    return self._get_source_fast(environment, template)
  File "E:\ZURA KOPADZE\mapping_stca\venv\lib\site-packages\flask\templating.py", line 98, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: map.html
2024-12-28 18:27:20,575 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 18:27:20] "[35m[1mGET /index HTTP/1.1[0m" 500 -
2024-12-28 18:27:43,170 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 18:27:43] "GET / HTTP/1.1" 200 -
2024-12-28 18:27:43,199 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 18:27:43] "[36mGET /static/css/Login_page.css HTTP/1.1[0m" 304 -
2024-12-28 18:27:43,301 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 18:27:43] "[33mGET /static/images/background.jpg HTTP/1.1[0m" 404 -
2024-12-28 18:27:48,595 - INFO - main.py - User 'zura' logged in successfully.
2024-12-28 18:27:48,596 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 18:27:48] "[32mPOST / HTTP/1.1[0m" 302 -
2024-12-28 18:27:48,616 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 18:27:48] "GET /index HTTP/1.1" 200 -
2024-12-28 18:27:48,652 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 18:27:48] "[36mGET /static/css/map_page.css HTTP/1.1[0m" 304 -
2024-12-28 18:28:02,188 - INFO - main.py - User 'zura' submitted filter data: start_date=2024-10-16, end_date=2024-12-28, callsign_filter=both, id_filter=.
2024-12-28 18:28:03,748 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 18:28:03] "POST /index HTTP/1.1" 200 -
2024-12-28 18:28:03,789 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 18:28:03] "[36mGET /static/css/map_page.css HTTP/1.1[0m" 304 -
2024-12-28 18:28:03,902 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 18:28:03] "GET /Results/map.html HTTP/1.1" 200 -
2024-12-28 18:28:12,856 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 18:28:12] "[36mGET /static/css/map_page.css HTTP/1.1[0m" 304 -
2024-12-28 19:09:44,263 - INFO - main.py - User 'zura' submitted filter data: start_date=2024-10-28, end_date=2024-11-28, callsign_filter=both, id_filter=AZO7030.
2024-12-28 19:09:44,301 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 19:09:44] "POST /index HTTP/1.1" 200 -
2024-12-28 19:09:44,369 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 19:09:44] "[36mGET /static/css/map_page.css HTTP/1.1[0m" 304 -
2024-12-28 19:09:44,491 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 19:09:44] "GET /Results/map.html HTTP/1.1" 200 -
2024-12-28 19:09:54,997 - INFO - main.py - Flask application is shutting down.
2024-12-28 19:10:03,325 - INFO - _internal.py - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://172.16.12.13:80
2024-12-28 19:10:03,325 - INFO - _internal.py - [33mPress CTRL+C to quit[0m
2024-12-28 20:19:18,467 - INFO - main.py - Flask application is shutting down.
2024-12-28 20:19:24,755 - INFO - _internal.py - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://172.16.12.13:80
2024-12-28 20:19:24,755 - INFO - _internal.py - [33mPress CTRL+C to quit[0m
2024-12-28 20:19:31,878 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 20:19:31] "GET / HTTP/1.1" 200 -
2024-12-28 20:19:31,934 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 20:19:31] "[36mGET /static/css/Login_page.css HTTP/1.1[0m" 304 -
2024-12-28 20:19:31,997 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 20:19:31] "[33mGET /static/images/background.jpg HTTP/1.1[0m" 404 -
2024-12-28 20:19:36,788 - INFO - main.py - User 'zura' logged in successfully.
2024-12-28 20:19:36,789 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 20:19:36] "[32mPOST / HTTP/1.1[0m" 302 -
2024-12-28 20:19:36,842 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 20:19:36] "GET /index HTTP/1.1" 200 -
2024-12-28 20:19:36,873 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 20:19:36] "[36mGET /static/css/map_page.css HTTP/1.1[0m" 304 -
2024-12-28 20:19:46,737 - INFO - main.py - User 'zura' submitted filter data: start_date=2024-07-28, end_date=2024-12-28, callsign_filter=both, id_filter=.
2024-12-28 20:19:50,496 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 20:19:50] "POST /index HTTP/1.1" 200 -
2024-12-28 20:19:50,526 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 20:19:50] "[36mGET /static/css/map_page.css HTTP/1.1[0m" 304 -
2024-12-28 20:19:50,614 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 20:19:50] "GET /Results/map.html HTTP/1.1" 200 -
2024-12-28 20:20:18,269 - INFO - _internal.py - 172.16.12.13 - - [28/Dec/2024 20:20:18] "GET / HTTP/1.1" 200 -
2024-12-28 20:20:18,372 - INFO - _internal.py - 172.16.12.13 - - [28/Dec/2024 20:20:18] "GET /static/css/Login_page.css HTTP/1.1" 200 -
2024-12-28 20:20:18,484 - INFO - _internal.py - 172.16.12.13 - - [28/Dec/2024 20:20:18] "[33mGET /static/images/background.jpg HTTP/1.1[0m" 404 -
2024-12-28 20:20:27,554 - INFO - main.py - User 'zura' logged in successfully.
2024-12-28 20:20:27,555 - INFO - _internal.py - 172.16.12.13 - - [28/Dec/2024 20:20:27] "[32mPOST / HTTP/1.1[0m" 302 -
2024-12-28 20:20:27,566 - INFO - _internal.py - 172.16.12.13 - - [28/Dec/2024 20:20:27] "GET /index HTTP/1.1" 200 -
2024-12-28 20:20:27,679 - INFO - _internal.py - 172.16.12.13 - - [28/Dec/2024 20:20:27] "GET /static/css/map_page.css HTTP/1.1" 200 -
2024-12-28 20:20:37,742 - INFO - _internal.py - 172.16.12.13 - - [28/Dec/2024 20:20:37] "GET /index HTTP/1.1" 200 -
2024-12-28 20:20:37,788 - INFO - _internal.py - 172.16.12.13 - - [28/Dec/2024 20:20:37] "[36mGET /static/css/map_page.css HTTP/1.1[0m" 304 -
2024-12-28 20:22:15,704 - INFO - main.py - User 'zura' submitted filter data: start_date=2024-07-28, end_date=2024-12-28, callsign_filter=both, id_filter=.
2024-12-28 20:22:19,596 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 20:22:19] "POST /index HTTP/1.1" 200 -
2024-12-28 20:22:19,643 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 20:22:19] "[36mGET /static/css/map_page.css HTTP/1.1[0m" 304 -
2024-12-28 20:22:19,674 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 20:22:19] "GET /Results/map.html HTTP/1.1" 200 -
2024-12-28 20:22:22,661 - INFO - main.py - User 'zura' submitted filter data: start_date=2024-07-28, end_date=2024-12-28, callsign_filter=Real, id_filter=.
2024-12-28 20:22:23,149 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 20:22:23] "POST /index HTTP/1.1" 200 -
2024-12-28 20:22:23,173 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 20:22:23] "[36mGET /static/css/map_page.css HTTP/1.1[0m" 304 -
2024-12-28 20:22:23,341 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 20:22:23] "GET /Results/map.html HTTP/1.1" 200 -
2024-12-28 20:24:08,028 - INFO - main.py - User 'zura' submitted filter data: start_date=2024-07-28, end_date=2024-12-28, callsign_filter=Suspicious, id_filter=EKGEO.
2024-12-28 20:24:08,049 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 20:24:08] "POST /index HTTP/1.1" 200 -
2024-12-28 20:24:08,076 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 20:24:08] "[36mGET /static/css/map_page.css HTTP/1.1[0m" 304 -
2024-12-28 20:24:12,781 - INFO - main.py - User 'zura' submitted filter data: start_date=2024-07-28, end_date=2024-12-28, callsign_filter=Suspicious, id_filter=EKGEO.
2024-12-28 20:24:12,802 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 20:24:12] "POST /index HTTP/1.1" 200 -
2024-12-28 20:24:12,825 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 20:24:12] "[36mGET /static/css/map_page.css HTTP/1.1[0m" 304 -
2024-12-28 20:24:14,141 - INFO - main.py - User 'zura' submitted filter data: start_date=2024-07-28, end_date=2024-12-28, callsign_filter=Suspicious, id_filter=.
2024-12-28 20:24:17,446 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 20:24:17] "POST /index HTTP/1.1" 200 -
2024-12-28 20:24:17,484 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 20:24:17] "[36mGET /static/css/map_page.css HTTP/1.1[0m" 304 -
2024-12-28 20:24:17,545 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 20:24:17] "GET /Results/map.html HTTP/1.1" 200 -
2024-12-28 20:24:25,108 - INFO - main.py - User 'zura' submitted filter data: start_date=2024-07-28, end_date=2024-12-28, callsign_filter=Suspicious, id_filter=5365.
2024-12-28 20:24:25,150 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 20:24:25] "POST /index HTTP/1.1" 200 -
2024-12-28 20:24:25,183 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 20:24:25] "[36mGET /static/css/map_page.css HTTP/1.1[0m" 304 -
2024-12-28 20:24:25,239 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 20:24:25] "GET /Results/map.html HTTP/1.1" 200 -
2024-12-28 20:24:27,646 - INFO - main.py - User 'zura' submitted filter data: start_date=2024-07-28, end_date=2024-12-28, callsign_filter=Suspicious, id_filter=.
2024-12-28 20:24:30,998 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 20:24:30] "POST /index HTTP/1.1" 200 -
2024-12-28 20:24:31,033 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 20:24:31] "[36mGET /static/css/map_page.css HTTP/1.1[0m" 304 -
2024-12-28 20:24:31,111 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 20:24:31] "GET /Results/map.html HTTP/1.1" 200 -
2024-12-28 20:24:36,034 - INFO - main.py - User 'zura' submitted filter data: start_date=2024-07-28, end_date=2024-12-28, callsign_filter=Real, id_filter=.
2024-12-28 20:24:36,509 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 20:24:36] "POST /index HTTP/1.1" 200 -
2024-12-28 20:24:36,542 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 20:24:36] "[36mGET /static/css/map_page.css HTTP/1.1[0m" 304 -
2024-12-28 20:24:36,713 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 20:24:36] "GET /Results/map.html HTTP/1.1" 200 -
2024-12-28 20:24:43,508 - INFO - main.py - User 'zura' submitted filter data: start_date=2024-07-28, end_date=2024-12-28, callsign_filter=Real, id_filter=EKGEO.
2024-12-28 20:24:43,544 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 20:24:43] "POST /index HTTP/1.1" 200 -
2024-12-28 20:24:43,573 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 20:24:43] "[36mGET /static/css/map_page.css HTTP/1.1[0m" 304 -
2024-12-28 20:24:43,640 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 20:24:43] "GET /Results/map.html HTTP/1.1" 200 -
2024-12-28 20:24:55,972 - INFO - main.py - User 'zura' submitted filter data: start_date=2024-07-28, end_date=2024-12-28, callsign_filter=Real, id_filter= VAA010.
2024-12-28 20:24:55,992 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 20:24:55] "POST /index HTTP/1.1" 200 -
2024-12-28 20:24:56,018 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 20:24:56] "[36mGET /static/css/map_page.css HTTP/1.1[0m" 304 -
2024-12-28 20:25:04,991 - INFO - main.py - User 'zura' submitted filter data: start_date=2024-07-28, end_date=2024-12-28, callsign_filter=Real, id_filter=VAA010 .
2024-12-28 20:25:05,012 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 20:25:05] "POST /index HTTP/1.1" 200 -
2024-12-28 20:25:05,038 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 20:25:05] "[36mGET /static/css/map_page.css HTTP/1.1[0m" 304 -
2024-12-28 20:25:07,883 - INFO - main.py - User 'zura' submitted filter data: start_date=2024-07-28, end_date=2024-12-28, callsign_filter=Real, id_filter=EKGEO.
2024-12-28 20:25:07,920 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 20:25:07] "POST /index HTTP/1.1" 200 -
2024-12-28 20:25:07,945 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 20:25:07] "[36mGET /static/css/map_page.css HTTP/1.1[0m" 304 -
2024-12-28 20:25:08,011 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 20:25:08] "GET /Results/map.html HTTP/1.1" 200 -
2024-12-28 20:25:21,891 - INFO - main.py - User 'zura' submitted filter data: start_date=2024-07-28, end_date=2024-12-28, callsign_filter=Real, id_filter=.
2024-12-28 20:25:22,374 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 20:25:22] "POST /index HTTP/1.1" 200 -
2024-12-28 20:25:22,401 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 20:25:22] "[36mGET /static/css/map_page.css HTTP/1.1[0m" 304 -
2024-12-28 20:25:22,475 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 20:25:22] "GET /Results/map.html HTTP/1.1" 200 -
2024-12-28 20:25:31,969 - INFO - main.py - User 'zura' submitted filter data: start_date=2024-07-28, end_date=2024-12-28, callsign_filter=Real, id_filter=TWB401.
2024-12-28 20:25:32,011 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 20:25:32] "POST /index HTTP/1.1" 200 -
2024-12-28 20:25:32,036 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 20:25:32] "[36mGET /static/css/map_page.css HTTP/1.1[0m" 304 -
2024-12-28 20:25:32,136 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 20:25:32] "GET /Results/map.html HTTP/1.1" 200 -
2024-12-28 20:25:56,258 - INFO - main.py - User 'zura' submitted filter data: start_date=2024-07-28, end_date=2024-12-28, callsign_filter=Real, id_filter=.
2024-12-28 20:25:56,815 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 20:25:56] "POST /index HTTP/1.1" 200 -
2024-12-28 20:25:56,842 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 20:25:56] "[36mGET /static/css/map_page.css HTTP/1.1[0m" 304 -
2024-12-28 20:25:56,907 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 20:25:56] "GET /Results/map.html HTTP/1.1" 200 -
2024-12-28 20:26:17,037 - INFO - main.py - User 'zura' submitted filter data: start_date=2024-07-28, end_date=2024-12-28, callsign_filter=Real, id_filter= aWRWEG .
2024-12-28 20:26:17,059 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 20:26:17] "POST /index HTTP/1.1" 200 -
2024-12-28 20:26:17,081 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 20:26:17] "[36mGET /static/css/map_page.css HTTP/1.1[0m" 304 -
2024-12-28 20:26:19,087 - INFO - main.py - User 'zura' submitted filter data: start_date=2024-07-28, end_date=2024-12-28, callsign_filter=Real, id_filter=.
2024-12-28 20:26:19,584 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 20:26:19] "POST /index HTTP/1.1" 200 -
2024-12-28 20:26:19,610 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 20:26:19] "[36mGET /static/css/map_page.css HTTP/1.1[0m" 304 -
2024-12-28 20:26:19,682 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 20:26:19] "GET /Results/map.html HTTP/1.1" 200 -
2024-12-28 20:26:29,245 - INFO - main.py - User 'zura' submitted filter data: start_date=2024-07-28, end_date=2024-12-28, callsign_filter=both, id_filter=.
2024-12-28 20:26:32,948 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 20:26:32] "POST /index HTTP/1.1" 200 -
2024-12-28 20:26:32,975 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 20:26:32] "[36mGET /static/css/map_page.css HTTP/1.1[0m" 304 -
2024-12-28 20:26:33,045 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 20:26:33] "GET /Results/map.html HTTP/1.1" 200 -
2024-12-28 20:26:40,612 - INFO - main.py - User 'zura' submitted filter data: start_date=2024-07-28, end_date=2024-12-28, callsign_filter=Suspicious, id_filter=EKGEO.
2024-12-28 20:26:40,634 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 20:26:40] "POST /index HTTP/1.1" 200 -
2024-12-28 20:26:40,659 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 20:26:40] "[36mGET /static/css/map_page.css HTTP/1.1[0m" 304 -
2024-12-28 20:26:53,156 - INFO - main.py - User 'zura' submitted filter data: start_date=2024-07-28, end_date=2024-12-28, callsign_filter=both, id_filter=EKGEO.
2024-12-28 20:26:53,192 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 20:26:53] "POST /index HTTP/1.1" 200 -
2024-12-28 20:26:53,217 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 20:26:53] "[36mGET /static/css/map_page.css HTTP/1.1[0m" 304 -
2024-12-28 20:26:53,301 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 20:26:53] "GET /Results/map.html HTTP/1.1" 200 -
2024-12-28 20:27:15,973 - INFO - main.py - User 'zura' submitted filter data: start_date=2024-07-28, end_date=2024-12-28, callsign_filter=both, id_filter=.
2024-12-28 20:27:19,774 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 20:27:19] "POST /index HTTP/1.1" 200 -
2024-12-28 20:27:19,809 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 20:27:19] "[36mGET /static/css/map_page.css HTTP/1.1[0m" 304 -
2024-12-28 20:27:19,883 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 20:27:19] "GET /Results/map.html HTTP/1.1" 200 -
2024-12-28 20:27:47,597 - INFO - main.py - User 'zura' submitted filter data: start_date=2024-07-28, end_date=2024-12-28, callsign_filter=Suspicious, id_filter=VAA010.
2024-12-28 20:27:47,619 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 20:27:47] "POST /index HTTP/1.1" 200 -
2024-12-28 20:27:47,645 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 20:27:47] "[36mGET /static/css/map_page.css HTTP/1.1[0m" 304 -
2024-12-28 20:27:53,877 - INFO - main.py - User 'zura' submitted filter data: start_date=2024-07-28, end_date=2024-12-28, callsign_filter=both, id_filter=VAA010.
2024-12-28 20:27:53,915 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 20:27:53] "POST /index HTTP/1.1" 200 -
2024-12-28 20:27:53,944 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 20:27:53] "[36mGET /static/css/map_page.css HTTP/1.1[0m" 304 -
2024-12-28 20:27:54,009 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 20:27:54] "GET /Results/map.html HTTP/1.1" 200 -
2024-12-28 20:29:56,574 - INFO - main.py - User 'zura' submitted filter data: start_date=2024-07-28, end_date=2024-12-28, callsign_filter=both, id_filter=VAA010.
2024-12-28 20:29:56,610 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 20:29:56] "POST /index HTTP/1.1" 200 -
2024-12-28 20:29:56,639 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 20:29:56] "[36mGET /static/css/map_page.css HTTP/1.1[0m" 304 -
2024-12-28 20:29:56,715 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 20:29:56] "GET /Results/map.html HTTP/1.1" 200 -
2024-12-28 20:30:10,862 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 20:30:10] "GET /index HTTP/1.1" 200 -
2024-12-28 20:30:10,886 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 20:30:10] "[36mGET /static/css/map_page.css HTTP/1.1[0m" 304 -
2024-12-28 20:30:17,458 - INFO - main.py - User 'zura' logged out successfully.
2024-12-28 20:30:17,459 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 20:30:17] "[32mGET /logout HTTP/1.1[0m" 302 -
2024-12-28 20:30:17,475 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 20:30:17] "GET / HTTP/1.1" 200 -
2024-12-28 20:30:17,510 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 20:30:17] "[36mGET /static/css/Login_page.css HTTP/1.1[0m" 304 -
2024-12-28 20:30:17,554 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 20:30:17] "[33mGET /static/images/background.jpg HTTP/1.1[0m" 404 -
2024-12-28 20:30:20,610 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 20:30:20] "[31m[1mGET /index HTTP/1.1[0m" 401 -
2024-12-28 20:30:24,455 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 20:30:24] "GET / HTTP/1.1" 200 -
2024-12-28 20:30:24,485 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 20:30:24] "[36mGET /static/css/Login_page.css HTTP/1.1[0m" 304 -
2024-12-28 20:30:29,880 - WARNING - main.py - Failed login attempt for username: 'zura'.
2024-12-28 20:30:29,882 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 20:30:29] "POST / HTTP/1.1" 200 -
2024-12-28 20:30:29,905 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 20:30:29] "[36mGET /static/css/Login_page.css HTTP/1.1[0m" 304 -
2024-12-28 20:30:35,410 - WARNING - main.py - Failed login attempt for username: 'zura'.
2024-12-28 20:30:35,411 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 20:30:35] "POST / HTTP/1.1" 200 -
2024-12-28 20:30:35,431 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 20:30:35] "[36mGET /static/css/Login_page.css HTTP/1.1[0m" 304 -
2024-12-28 20:30:43,506 - INFO - main.py - User 'zura' logged in successfully.
2024-12-28 20:30:43,507 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 20:30:43] "[32mPOST / HTTP/1.1[0m" 302 -
2024-12-28 20:30:43,517 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 20:30:43] "GET /index HTTP/1.1" 200 -
2024-12-28 20:30:43,538 - INFO - _internal.py - 127.0.0.1 - - [28/Dec/2024 20:30:43] "[36mGET /static/css/map_page.css HTTP/1.1[0m" 304 -
2024-12-28 20:31:01,551 - INFO - main.py - Flask application is shutting down.
2024-12-29 09:06:29,656 - INFO - _internal.py - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://172.16.12.13:80
2024-12-29 09:06:29,656 - INFO - _internal.py - [33mPress CTRL+C to quit[0m
2024-12-29 09:06:42,950 - INFO - _internal.py - 127.0.0.1 - - [29/Dec/2024 09:06:42] "GET / HTTP/1.1" 200 -
2024-12-29 09:06:42,972 - INFO - _internal.py - 127.0.0.1 - - [29/Dec/2024 09:06:42] "[36mGET /static/css/Login_page.css HTTP/1.1[0m" 304 -
2024-12-29 09:06:42,981 - INFO - _internal.py - 127.0.0.1 - - [29/Dec/2024 09:06:42] "[33mGET /static/images/background.jpg HTTP/1.1[0m" 404 -
2024-12-29 09:06:48,021 - INFO - main.py - User 'zura' logged in successfully.
2024-12-29 09:06:48,023 - INFO - _internal.py - 127.0.0.1 - - [29/Dec/2024 09:06:48] "[32mPOST / HTTP/1.1[0m" 302 -
2024-12-29 09:06:48,040 - INFO - _internal.py - 127.0.0.1 - - [29/Dec/2024 09:06:48] "GET /index HTTP/1.1" 200 -
2024-12-29 09:06:48,072 - INFO - _internal.py - 127.0.0.1 - - [29/Dec/2024 09:06:48] "[36mGET /static/css/map_page.css HTTP/1.1[0m" 304 -
2024-12-29 09:06:55,283 - INFO - main.py - User 'zura' submitted filter data: start_date=2024-07-12, end_date=2024-12-29, callsign_filter=both, id_filter=.
2024-12-29 09:06:59,248 - INFO - _internal.py - 127.0.0.1 - - [29/Dec/2024 09:06:59] "POST /index HTTP/1.1" 200 -
2024-12-29 09:06:59,276 - INFO - _internal.py - 127.0.0.1 - - [29/Dec/2024 09:06:59] "[36mGET /static/css/map_page.css HTTP/1.1[0m" 304 -
2024-12-29 09:06:59,344 - INFO - _internal.py - 127.0.0.1 - - [29/Dec/2024 09:06:59] "GET /Results/map.html HTTP/1.1" 200 -
2024-12-29 09:07:16,368 - INFO - main.py - User 'zura' logged out successfully.
2024-12-29 09:07:16,369 - INFO - _internal.py - 127.0.0.1 - - [29/Dec/2024 09:07:16] "[32mGET /logout HTTP/1.1[0m" 302 -
2024-12-29 09:07:16,383 - INFO - _internal.py - 127.0.0.1 - - [29/Dec/2024 09:07:16] "GET / HTTP/1.1" 200 -
2024-12-29 09:07:16,417 - INFO - _internal.py - 127.0.0.1 - - [29/Dec/2024 09:07:16] "[36mGET /static/css/Login_page.css HTTP/1.1[0m" 304 -
2024-12-29 09:07:16,532 - INFO - _internal.py - 127.0.0.1 - - [29/Dec/2024 09:07:16] "[33mGET /static/images/background.jpg HTTP/1.1[0m" 404 -
2024-12-29 09:10:13,730 - INFO - main.py - Flask application is shutting down.
